baseURL = "https://dynamicdesignmechanicalengineers.com"
disableLanguages = ["fr"]
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
paginate = "4"
summaryLength = "30"
theme = "airspace-hugo"
title = "Dynamic Design Mechanicsl Engineers"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2021 [Dynamics Design Mechanical Engineers]() All Rights Reserved"
home = "Home"
languageCode = "en-uk"
languageName = "En"
weight = 1
[[menu.footer]]
URL = "contact"
name = "Contact"
weight = 2
[[menu.footer]]
URL = "service"
name = "Service"
weight = 1
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 3
[[menu.main]]
URL = "https://www.adriaansblog.com/"
name = "Blog"
weight = 2
[[menu.main]]
URL = "service"
name = "Service"
weight = 1
[params]
author = "Adriaan van Niekerk"
contact_form_action = "https://formspree.io/xwkrvvrz"
description = "A innovative and performance driven engineering company"
email = "contact@dynamicdesignmechanicalengineers.com"
mobile = "testing"
google_analitycs_id = "UA-161404758-2"
location = "Bristol, United Kingdom"
logo = "images/logo.png"

multi_author = false
[params.gmap]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "51.511438"
map_longitude = "-2.542594"
map_marker = "images/marker.png"
[params.nav_button]
enable = false
label = "Get A Quote"
link = "contact"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = ""
[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]
[[params.social]]
icon = "ion-social-linkedin-outline"
link = "https://www.linkedin.com/in/adriaan-van-niekerk/"
[[params.social]]
icon = "ion-social-twitter-outline"
link = "https://twitter.com/asvn90"
